# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -Pprod clean install
      
    - name: copy file via ssh key
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.TURF_SERVER_IP }}
        username: ec2-user
        key: ${{ secrets.MEDICAL_STORE_KEY }}
        source: "target/*.jar"
        target: "builds"
        
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.TURF_SERVER_IP }}
        username: ec2-user
        key: ${{ secrets.MEDICAL_STORE_KEY }}
        script: |
          fuser -k -n tcp 7070
          fuser -k -n tcp 7070
          fuser -k -n tcp 7070
          fuser -k -n tcp 7070
          java -jar /home/ec2-user/builds/target/*.jar > /home/ec2-user/builds/target/turf-server-logs.txt 2>&1 &
          
