# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn clean install
      
    - name: copy file via ssh key
      uses: appleboy/scp-action@master
      with:
        host: ec2-65-0-18-78.ap-south-1.compute.amazonaws.com
        username: ubuntu
        key: ${{ secrets.SERVER_KEY }}
        source: "target/*.jar"
        target: "builds"
        
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ec2-65-0-18-78.ap-south-1.compute.amazonaws.com
        username: ubuntu
        key: ${{ secrets.SERVER_KEY }}
        script: |
          fuser -k -n tcp 8080
          fuser -k -n tcp 8080
          fuser -k -n tcp 8080
          fuser -k -n tcp 8080
          java -jar /home/ubuntu/builds/target/*.jar > /home/ubuntu/builds/target/server-logs.txt 2>&1 &
          
